version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    command: ["denon", "run", "--allow-all", "--node-modules-dir", "src/index.ts"]
    volumes:
      - .:/app
    env_file:
      - .env
